services:
  web:
    build: .
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:cached
      - uploads_data:/var/www/html/uploads:delegated  # Changed to named volume
      - /tmp:/tmp:delegated
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_NAME=soc_pms
      - DB_USER=dbuser
      - DB_PASS=dbpassword
      - UPLOAD_MAX_FILESIZE=20M
      - POST_MAX_SIZE=21M

  db:
    image: mariadb:lts-ubi9
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=12345678
      - MARIADB_DATABASE=soc_pms
      - MARIADB_USER=dbuser
      - MARIADB_PASSWORD=dbpassword
      - MARIADB_ROOT_HOST=%  # Allow root access from any host
      - MARIADB_CHARACTER_SET_SERVER=utf8mb4
      - MARIADB_COLLATION_SERVER=utf8mb4_general_ci
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --skip-innodb-doublewrite
      --max_allowed_packet=256M
      --wait_timeout=28800
      --innodb_buffer_pool_size=256M
      --innodb-use-native-aio=0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p12345678"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=12345678
    depends_on:
      - db
    command: >
      bash -c "echo 'ServerName localhost' >> /etc/apache2/apache2.conf && apache2-foreground"

volumes:
  mysql_data:
    driver: local
  uploads_data:  # Add new named volume
    driver: local